name: update

on: [push, pull_request]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get Lastest 7z
      run: |
        curl -fsSL "http://sourceforge.net/projects/sevenzip/files/latest/download?source=files" -o "./7z.exe" -O
    - name: Extract 7z
      run: |
        7z x ./7z.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 7z
        path: "./7z/7z.exe"
